services:
    bot:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./data:/app/data
        restart: unless-stopped
        env_file: ".env"
        ports:
            - 13724:8000