[project]
name = "live-coding"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "arrow>=1.3.0",
    "python-dotenv>=1.1.1",
    "slack-sdk>=3.36.0",
]
